"""enum column types

Revision ID: 232aa15fb29e
Revises: 1f58d631c4d7
Create Date: 2026-03-08 00:23:06.633627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '232aa15fb29e'
down_revision: Union[str, Sequence[str], None] = '1f58d631c4d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('CHECKING', 'SAVINGS', 'CASH', 'CREDIT', name='accounttype', native_enum=False),
               existing_nullable=False)

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('INCOME', 'EXPENSE', name='categorytype', native_enum=False),
               existing_nullable=False)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('INCOME', 'EXPENSE', 'TRANSFER', name='transactiontype', native_enum=False),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.Enum('INCOME', 'EXPENSE', 'TRANSFER', name='transactiontype', native_enum=False),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.Enum('INCOME', 'EXPENSE', name='categorytype', native_enum=False),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.Enum('CHECKING', 'SAVINGS', 'CASH', 'CREDIT', name='accounttype', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###
