"""add_institutions

Revision ID: 75ce3b1f4e5a
Revises: 232aa15fb29e
Create Date: 2026-03-08 01:35:57.376430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75ce3b1f4e5a'
down_revision: Union[str, Sequence[str], None] = '232aa15fb29e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Enum('BANK', 'FINTECH', 'CREDIT_UNION', 'BROKER', 'INSURANCE', 'OTHER', name='institutiontype', native_enum=False), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('website', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('institution_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_accounts_institution_id', 'institutions', ['institution_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_accounts_institution_id', type_='foreignkey')
        batch_op.drop_column('institution_id')

    op.drop_table('institutions')
    # ### end Alembic commands ###
