# SPDX-License-Identifier: AGPL-3.0-or-later
"""Settings page default values for user storage keys."""

from __future__ import annotations

from decimal import Decimal

DEFAULT_DATE_FORMAT = "iso"
DEFAULT_WEEK_START = "monday"
DEFAULT_SUBSCRIPTIONS_DETECTOR_DAYS = 730
DEFAULT_HOUSEKEEPING_DUPLICATE_DAYS = 365
DEFAULT_PAYMENT_CALENDAR_OVERDUE_DAYS = 30
DEFAULT_AUTO_POST_DUE_ON_STARTUP = False
DEFAULT_NUMBER_FORMAT = "eu"
DEFAULT_BUDGET_MONTH_START_DAY = 1
DEFAULT_TRANSFER_PAIRING_DAYS = 3
DEFAULT_TRANSFER_AMOUNT_TOLERANCE = Decimal("0.01")
DEFAULT_PAYEE_DEDUPE_MAX_DISTANCE = 2
DEFAULT_IMPORT_SKIP_DUPLICATES = True
DEFAULT_EVENTS_ENABLED = True
DEFAULT_EVENT_RETENTION_DAYS = 7

__all__ = [
    "DEFAULT_DATE_FORMAT",
    "DEFAULT_WEEK_START",
    "DEFAULT_SUBSCRIPTIONS_DETECTOR_DAYS",
    "DEFAULT_HOUSEKEEPING_DUPLICATE_DAYS",
    "DEFAULT_PAYMENT_CALENDAR_OVERDUE_DAYS",
    "DEFAULT_AUTO_POST_DUE_ON_STARTUP",
    "DEFAULT_NUMBER_FORMAT",
    "DEFAULT_BUDGET_MONTH_START_DAY",
    "DEFAULT_TRANSFER_PAIRING_DAYS",
    "DEFAULT_TRANSFER_AMOUNT_TOLERANCE",
    "DEFAULT_PAYEE_DEDUPE_MAX_DISTANCE",
    "DEFAULT_IMPORT_SKIP_DUPLICATES",
    "DEFAULT_EVENTS_ENABLED",
    "DEFAULT_EVENT_RETENTION_DAYS",
]
