# SPDX-License-Identifier: AGPL-3.0-or-later
"""Settings page default values for user storage keys."""

from __future__ import annotations

from decimal import Decimal

from kaleta.core.weeks import DEFAULT_WEEK_START_MODE as _DEFAULT_WEEK_START_MODE

DEFAULT_DATE_FORMAT = "iso"
DEFAULT_WEEK_START = "monday"
#: Which of ``kaleta.core.weeks.WeekStartMode`` a fresh install buckets by.
DEFAULT_WEEK_START_MODE = str(_DEFAULT_WEEK_START_MODE)
DEFAULT_SUBSCRIPTIONS_DETECTOR_DAYS = 730
DEFAULT_HOUSEKEEPING_DUPLICATE_DAYS = 365
DEFAULT_PAYMENT_CALENDAR_OVERDUE_DAYS = 30
DEFAULT_AUTO_POST_DUE_ON_STARTUP = False
DEFAULT_NUMBER_FORMAT = "eu"
DEFAULT_BUDGET_MONTH_START_DAY = 1
DEFAULT_TRANSFER_PAIRING_DAYS = 3
DEFAULT_TRANSFER_AMOUNT_TOLERANCE = Decimal("0.01")
DEFAULT_PAYEE_DEDUPE_MAX_DISTANCE = 2
DEFAULT_IMPORT_SKIP_DUPLICATES = True
DEFAULT_EVENTS_ENABLED = True
DEFAULT_EVENT_RETENTION_DAYS = 7
DEFAULT_TRANSACTIONS_UPCOMING_DAYS = 7
#: The only windows the ledger offers for upcoming planned rows. ``0`` is off.
TRANSACTIONS_UPCOMING_DAYS_CHOICES = (0, 7, 30)

__all__ = [
    "DEFAULT_AUTO_POST_DUE_ON_STARTUP",
    "DEFAULT_BUDGET_MONTH_START_DAY",
    "DEFAULT_DATE_FORMAT",
    "DEFAULT_EVENTS_ENABLED",
    "DEFAULT_EVENT_RETENTION_DAYS",
    "DEFAULT_HOUSEKEEPING_DUPLICATE_DAYS",
    "DEFAULT_IMPORT_SKIP_DUPLICATES",
    "DEFAULT_NUMBER_FORMAT",
    "DEFAULT_PAYEE_DEDUPE_MAX_DISTANCE",
    "DEFAULT_PAYMENT_CALENDAR_OVERDUE_DAYS",
    "DEFAULT_SUBSCRIPTIONS_DETECTOR_DAYS",
    "DEFAULT_TRANSACTIONS_UPCOMING_DAYS",
    "DEFAULT_TRANSFER_AMOUNT_TOLERANCE",
    "DEFAULT_TRANSFER_PAIRING_DAYS",
    "DEFAULT_WEEK_START",
    "DEFAULT_WEEK_START_MODE",
    "TRANSACTIONS_UPCOMING_DAYS_CHOICES",
]
