# SPDX-License-Identifier: AGPL-3.0-or-later
"""Settings page default values for user storage keys."""

from __future__ import annotations

DEFAULT_DATE_FORMAT = "iso"
DEFAULT_WEEK_START = "monday"
DEFAULT_SUBSCRIPTIONS_DETECTOR_DAYS = 730
DEFAULT_HOUSEKEEPING_DUPLICATE_DAYS = 365
DEFAULT_PAYMENT_CALENDAR_OVERDUE_DAYS = 30

__all__ = [
    "DEFAULT_DATE_FORMAT",
    "DEFAULT_WEEK_START",
    "DEFAULT_SUBSCRIPTIONS_DETECTOR_DAYS",
    "DEFAULT_HOUSEKEEPING_DUPLICATE_DAYS",
    "DEFAULT_PAYMENT_CALENDAR_OVERDUE_DAYS",
]
